using System.Linq;
using Xunit;
using Sudoku.ViewModels;

namespace Sudoku.UI.Tests;

public class MainViewModelTests
{
    [Fact]
    public void Constructor_ShouldInitialiseBoardWith81Cells()
    {
        var viewModel = new MainViewModel();
        Assert.NotNull(viewModel.Board);
        Assert.Equal(81, viewModel.Board.Count);
    }
    [Fact]
    public void SelectCell_UpdatesSelectedCellPropertyAndTogglesFlags()
    {
        // Arrange
        var viewModel = new MainViewModel();
        var targetCell = viewModel.Board[0];
        var secondCell = viewModel.Board[1];

        // Act 1: Select first cell
        viewModel.SelectCellCommand.Execute(targetCell);

        // Assert 1
        Assert.Equal(targetCell, viewModel.SelectedCell);
        Assert.True(targetCell.IsSelected);

        // Act 2: Select second cell to verify previous cell unhighlights
        viewModel.SelectCellCommand.Execute(secondCell);

        // Assert 2
        Assert.False(targetCell.IsSelected);
        Assert.True(secondCell.IsSelected);
        Assert.Equal(secondCell, viewModel.SelectedCell);
    }

    [Fact]
    public void InputNumber_WhenCellIsGiven_DoesNotChangeValue()
    {
        // Arrange
        var viewModel = new MainViewModel();

        // Find a starting clue generated by the engine
        var givenCell = viewModel.Board.First(c => c.IsGiven);
        int originalValue = givenCell.Value;

        // Select the clue cell
        viewModel.SelectCellCommand.Execute(givenCell);

        // Act: Try inputting a new digit
        int newDigit = originalValue == 9 ? 1 : originalValue + 1;
        viewModel.InputNumber(newDigit);

        // Assert: Value remains unchanged
        Assert.Equal(originalValue, givenCell.Value);
    }

    [Fact]
    public void InputNumber_WhenCellIsEditable_UpdatesValueAndEngine()
    {
        // Arrange
        var viewModel = new MainViewModel();

        // Find an empty editable cell
        var editableCell = viewModel.Board.First(c => !c.IsGiven);
        viewModel.SelectCellCommand.Execute(editableCell);

        // Act
        viewModel.InputNumber(5);

        // Assert
        Assert.Equal(5, editableCell.Value);
    }

    [Fact]
    public void InputNumber_WhenDuplicateValueEnteredInRow_FlagsIsError()
    {
        // Arrange
        var viewModel = new MainViewModel();

        // Find an editable cell in row 0
        var editableCell = viewModel.Board.First(c => c.Row == 0 && !c.IsGiven);

        // Find an existing clue value in row 0
        var existingClue = viewModel.Board.First(c => c.Row == 0 && c.IsGiven);
        int duplicateDigit = existingClue.Value;

        viewModel.SelectCellCommand.Execute(editableCell);

        // Act: Input duplicate digit into the empty cell in the same row
        viewModel.InputNumber(duplicateDigit);

        // Assert: Cell correctly flags an error state
        Assert.True(editableCell.IsError);
    }

    [Fact]
    public void InputNumber_OnlyTrueSolutionValueClearsError()
    {
        // Arrange
        var viewModel = new MainViewModel();
        var editableCell = viewModel.Board.First(c => !c.IsGiven);
        viewModel.SelectCellCommand.Execute(editableCell);

        // Act: try every digit 1-9, including ones that don't conflict with any
        // existing row/column/box value but still don't match the true solution.
        int correctCount = 0;
        for (int digit = 1; digit <= 9; digit++)
        {
            viewModel.InputNumber(digit);

            if (!editableCell.IsError)
            {
                correctCount++;
            }
        }

        // Assert: exactly one digit (the true solution) should ever clear the error.
        Assert.Equal(1, correctCount);
    }

    [Fact]
    public void ClearSelectedCell_ResetsValueAndErrorState()
    {
        // Arrange
        var viewModel = new MainViewModel();
        var editableCell = viewModel.Board.First(c => !c.IsGiven);

        viewModel.SelectCellCommand.Execute(editableCell);
        viewModel.InputNumber(5);
        editableCell.IsError = true; // Simulate an error

        // Act
        viewModel.ClearSelectedCell();

        // Assert
        Assert.Equal(0, editableCell.Value);
        Assert.False(editableCell.IsError);
    }

    [Fact]
    public void UseHint_WhenNoCellSelected_SetsStatusMessageAndDoesNotThrow()
    {
        // Arrange
        var viewModel = new MainViewModel();

        // Act
        viewModel.UseHint();

        // Assert: no selection to reveal, so the user is guided instead
        Assert.Null(viewModel.SelectedCell);
        Assert.Equal("Select an empty cell to get a hint.", viewModel.StatusMessage);
    }

    [Fact]
    public void UseHint_WhenCellIsGiven_DoesNotChangeValue()
    {
        // Arrange
        var viewModel = new MainViewModel();

        // Find a starting clue generated by the engine
        var givenCell = viewModel.Board.First(c => c.IsGiven);
        int originalValue = givenCell.Value;

        viewModel.SelectCellCommand.Execute(givenCell);

        // Act
        viewModel.UseHint();

        // Assert: value untouched, same guard path as InputNumber/ClearSelectedCell
        Assert.Equal(originalValue, givenCell.Value);
    }

    [Fact]
    public void UseHint_WhenCellIsEditable_RevealsCorrectValueAndLocksCell()
    {
        // Arrange
        var viewModel = new MainViewModel();
        var editableCell = viewModel.Board.First(c => !c.IsGiven);
        viewModel.SelectCellCommand.Execute(editableCell);

        // Act
        viewModel.UseHint();

        // Assert: cell is filled with a valid, non-error value and locked like a starting clue
        Assert.NotEqual(0, editableCell.Value);
        Assert.False(editableCell.IsError);
        Assert.True(editableCell.IsGiven);
    }

    [Fact]
    public void UseHint_RevealedCellCanNoLongerBeEditedOrCleared()
    {
        // Arrange
        var viewModel = new MainViewModel();
        var editableCell = viewModel.Board.First(c => !c.IsGiven);
        viewModel.SelectCellCommand.Execute(editableCell);
        viewModel.UseHint();
        int hintedValue = editableCell.Value;

        // Act: try to overwrite, then try to erase, the now-locked cell
        int otherDigit = hintedValue == 9 ? 1 : hintedValue + 1;
        viewModel.InputNumber(otherDigit);
        viewModel.ClearSelectedCell();

        // Assert: value is unchanged, same as any other starting clue
        Assert.Equal(hintedValue, editableCell.Value);
    }
}